# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContactDeliveryAddresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_complete_addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_email_addresse', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_telephone_nr', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderContactInvoiceAddresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255, null=True)),
                ('complete_addresse', models.CharField(max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=15, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('email_addresse', models.EmailField(max_length=254, null=True)),
                ('telephone_nr', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
