# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderContact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontactdeliveryaddresse',
            name='delivery_complete_addresse',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontactdeliveryaddresse',
            name='delivery_organisation_name',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontactinvoiceaddresse',
            name='complete_addresse',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontactinvoiceaddresse',
            name='contact_person',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='ordercontactinvoiceaddresse',
            name='organisation_name',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
